# Common configuration properties.
set(VERSION_FILE_NAME "SPCDNS")
set(VERSION_PRODUCT_NAME "SPCDNS")
set(VERSION_SERVICE_PRODUCT_NAME "SPCDNS")
set(VERSION_PRODUCT_URL "www.conman.org/software/spcdns/")
set(VERSION_COMPANY_NAME "")

set(VERSION_COPYRIGHT "")
set(VERSION_DESCRIPTION "DNS library")

# Set current project version.
set(VERSION_MAJOR 2)
set(VERSION_MINOR 0)
set(VERSION_BUILD 8)

set(VERSION_FULL "${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_BUILD}")
set(VERSION_RC_FULL "${VERSION_MAJOR},${VERSION_MINOR},${VERSION_BUILD}")